name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-docker:
    runs-on: ubuntu-20.04
    container:
      image: swiftlang/swift:nightly-5.6-focal-slim
    steps:
      - name: Log swift version
        run: |
          swift --version