name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-docker:
    runs-on: ubuntu-20.04
    container:
      image: swiftlang/swift:nightly-5.6-focal
    steps:
      - name: Log swift version
        run: |
          swift --version
      - name: Step with docker
        uses: docker://swiftlang/swift:nightly-5.6-focal
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log swift version
        uses: docker://swiftlang/swift:nightly-5.6-focal
        with:
          entrypoint: '/usr/bin/swift'
          args: -v
