name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-docker:
    runs-on: ubuntu-20.04
    # container:
    #   image: swiftlang/swift:nightly-5.6-focal
    steps:
      - name: Log swift version
        run: |
          which swift
          swift --version
      - uses: actions/checkout@v2
      - name: Log swift version
        run: pwd; ls
      - name: Run a script
        run: $GITHUB_ACTION_PATH/script.sh
        shell: bash
