name: Generate Documentation

on:
  push:
  pull_request:

env:
  SCHEME_NAME: SquareLigatureEraNameDecomposer
  PATH_TO_DOCS_DIRECTORY: docs
  HOSTING_BASE_PATH: swift-docc-github-pages-playground

jobs:
  swift-docker:
    runs-on: ubuntu-20.04
    container:
      image: swiftlang/swift:nightly-5.6-focal
    steps:
      - name: Show Swift version
        run: swift --version
      - uses: actions/checkout@v2
      - name: Generate documentation
        run: |
          swift package --allow-writing-to-directory ${{ env.PATH_TO_DOCS_DIRECTORY }} \
          generate-documentation --target ${{ env.SCHEME_NAME }} \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path ${{ env.HOSTING_BASE_PATH }} \
          --output-path ${{ env.PATH_TO_DOCS_DIRECTORY }}
