name: Generate Documentation

on:
  workflow_run:
    workflows:
      - Swift Build & Test
    types:
      - completed

env:
  SCHEME_NAME: SquareLigatureEraNameDecomposer
  PATH_TO_DOCS_DIRECTORY: docs
  HOSTING_BASE_PATH: swift-docc-github-pages-playground

jobs:
  swift-docc-plugin:
    name: Generate documentation by Swift-DocC Plugin
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    container:
      image: swiftlang/swift:nightly-5.6-focal
    steps:
      - name: Show Swift version
        run: swift --version
      - uses: actions/checkout@v2
      - name: Generate documentation
        run: |
          swift package --allow-writing-to-directory ${{ env.PATH_TO_DOCS_DIRECTORY }} \
          generate-documentation --target ${{ env.SCHEME_NAME }} \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path ${{ env.HOSTING_BASE_PATH }} \
          --output-path ${{ env.PATH_TO_DOCS_DIRECTORY }}
      - name: Upload documentation to GitHub Pages
        uses: treastrain/github-pages-publish-action@v1
        with:
          path: ${{ env.PATH_TO_DOCS_DIRECTORY }}
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
